# Generated by Django 2.2.20 on 2021-04-21 10:54

from django.db import migrations


def update_field_new_building(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    new_building_flats = Flat.objects.filter(construction_year__gte="2015")
    for new_building_flat in new_building_flats:
        new_building_flat.new_building = True
        new_building_flat.save()

def move_backward(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    new_building_flats = Flat.objects.filter(new_building=True)
    for new_building_flat in new_building_flats:
        new_building_flat.new_building = None
        new_building_flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_flat_new_building"),
    ]

    operations = [
        migrations.RunPython(update_field_new_building, move_backward),
    ]
