# Generated by Django 2.2.20 on 2021-04-23 11:17
from django.db import migrations
from phonenumbers import is_valid_number, parse


def mutate_phone_numbers(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    flats = Flat.objects.all()
    for flat in flats:
        parsed_phone = parse(flat.owners_phonenumber, "RU")
        if not is_valid_number(parsed_phone):
            continue
        flat.owner_pure_phone = parsed_phone
        flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    flats = Flat.objects.all()
    for flat in flats:
        flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0008_flat_owner_pure_phone"),
    ]

    operations = [
        migrations.RunPython(mutate_phone_numbers, move_backward),
    ]
