# Generated by Django 2.2.20 on 2021-04-23 11:17
from phonenumbers import parse
from django.db import migrations


def mutate_phone_numbers(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    flats = Flat.objects.all()
    for flat in flats:
        flat.owner_pure_phone = parse(flat.owners_phonenumber, "RU")
        flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    flats = Flat.objects.all()
    for flat in flats:
        flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0008_flat_owner_pure_phone"),
    ]

    operations = [
        migrations.RunPython(mutate_phone_numbers, move_backward),
    ]
