# Generated by Django 2.2.20 on 2021-04-24 13:02

from django.db import migrations


def relocate_from_flat_to_owner(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")
    flats = Flat.objects.all()
    for flat in flats:
        Owner.objects.get_or_create(
            full_name=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone,
        )


def move_backward(apps, schema_editor):
    Owner = apps.get_model("property", "Owner")
    Owner.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0011_owner"),
    ]

    operations = [
        migrations.RunPython(relocate_from_flat_to_owner, move_backward),
    ]
