# Generated by Django 2.2.20 on 2021-04-24 13:35

from django.db import migrations


def link_owner_to_flat(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")
    owners = Owner.objects.all()
    for owner in owners:
        owner_flats = Flat.objects.filter(owner=owner.full_name)
        owner.flats.set(owner_flats)


def move_backward(apps, schema_editor):
    Owner = apps.get_model("property", "Owner")
    owners = Owner.objects.all()
    for owner in owners:
        owner.flats.clear()


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0012_auto_20210424_1602"),
    ]

    operations = [
        migrations.RunPython(link_owner_to_flat, move_backward),
    ]
